# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RQoUA3u14XcT83jteU3N59LOm47eT0l7
"""

import streamlit as st
import pandas as pd
import numpy as np
from catboost import CatBoostRegressor
from sklearn.preprocessing import StandardScaler
import joblib

model = joblib.load("model_catboost.pkl")
scaler = joblib.load("scaler.pkl")
numeric_features = joblib.load("features.pkl")  # Save the numeric feature list too

st.title("Calories Prediction App")

# User Inputs
age = st.number_input("Age", min_value=1)
height = st.number_input("Height (cm)", min_value=1)
weight = st.number_input("Weight (kg)", min_value=1)
duration = st.number_input("Duration (min)", min_value=1)
heart_rate = st.number_input("Heart Rate", min_value=1)
body_temp = st.number_input("Body Temperature (°C)", min_value=1.0)
sex = st.selectbox("Sex", ["male", "female"])

sex_encoded = 0 if sex == "male" else 1
input_data = pd.DataFrame([[age, height, weight, duration, heart_rate, body_temp, sex_encoded]],
                          columns=['Age', 'Height', 'Weight', 'Duration', 'Heart_Rate', 'Body_Temp', 'Sex'])

input_data[numeric_features] = scaler.transform(input_data[numeric_features])

# Predict
if st.button("Predict Calories Burned"):
    prediction = model.predict(input_data)
    st.success(f"Estimated Calories Burned: {prediction[0]:.2f} kcal")